/**
 * UDP
 */
export const UDP_NEW_MESSAGE = 'UDP_NEW_MESSAGE'
export const WALLBOX_FIRST_DATA = 'WALLLBOX_FIRST_DATA'
export const WALLBOX_ENABLE_CHANGE = 'WALLBOX_ENABLE_CHANGE'


export const CAR_PLUGGED_IN = 'CAR_PLUGGED_IN'
export const CAR_PLUGGED_OUT = 'CAR_PLUGGED_OUT'
export const CAR_PLUGGED_OUT_CHARGING = 'CAR_PLUGGED_OUT_CHARGING'
export const CAR_STARTED_CHARGING = 'CAR_STARTED_CHARGING'